### ISSUE TITLE
故障注入: practice/fault-injection.md

### ISSUE THREAD

**Issue by 3ks** [servicemesher/istio-handbook#103]
This article is waiting to be claimed. [practice/fault-injection.md](https://github.com/servicemesher/istio-handbook/tree/master/practice/fault-injection.md)

**Comment by tony-Ma-yami** [comment]
重新编排目录后, 这个issue已经有内容了, 是不是可以close掉了. 
https://www.servicemesher.com/istio-handbook/practice/fault-injection.html

**Comment by rootsongjc** [comment]
可以的，我关掉吧。
