### ISSUE TITLE
监控与可视化: practice/monitoring-visualization.md

### ISSUE THREAD

**Issue by 3ks** [servicemesher/istio-handbook#109]
This article is waiting to be claimed. [practice/monitoring-visualization.md](https://github.com/servicemesher/istio-handbook/tree/master/practice/monitoring-visualization.md)

**Comment by hb-chen** [comment]
子章节一同认领吗？

**Comment by rootsongjc** [comment]
@Lovnx 是把「监控与可视化」这一整章都认领了。
