### ISSUE TITLE
分布式追踪: practice/distributed-tracing.md

### ISSUE THREAD

**Issue by 3ks** [servicemesher/istio-handbook#115]
This article is waiting to be claimed. [practice/distributed-tracing.md](https://github.com/servicemesher/istio-handbook/tree/master/practice/distributed-tracing.md)

**Comment by rootsongjc** [comment]
统一下 Distributed tracing，本书中统一翻译为“分布式追踪”，不要再使用“分布式跟踪”、“分布式调用跟踪”和所有其他译法了。

**Comment by rootsongjc** [comment]
这篇文章 @zhaohuabing  已经在[另一篇](https://github.com/servicemesher/istio-handbook/pull/180)中写到一些，我提了个 [PR](https://github.com/servicemesher/istio-handbook/pull/187) 把他写的那些搬到这篇里了，@Lovnx 你可以在最新文档的基础上提交 PR。

**Comment by sniperking1234** [comment]
> Everyone can accept the issue now.

为什么取消了

**Comment by rootsongjc** [comment]
这篇文章已经完成，作者 @zhaohuabing，关闭此 issue。
