### ISSUE TITLE
“控制平面”章节下的描述有点小问题

### ISSUE THREAD

**Issue by tangyong** [servicemesher/istio-handbook#12]
http://www.servicemesher.com/istio-handbook/concepts-and-principle/service-mesh-architectures.html
中的“控制平面”章节下的描述有点小问题，如下：

“与控制平面中的代理通信，下发策略和配置” 应该是“与数据平面中的代理通信，下发策略和配置”

以上请确认。

**Comment by rootsongjc** [comment]
确实有问题，麻烦提交个 PR 修正下吧。@tangyong

**Comment by tangyong** [comment]
OK, 明天我来提交一下PULL Request
