### ISSUE TITLE
"Istio 架构解析"章节小错误

### ISSUE THREAD

**Issue by tangyong** [servicemesher/istio-handbook#14]
"Istio 架构解析"章节有一处小错误：

”Istio 是可定制可扩展的，组建是可拔插的” 应该是“Istio 是可定制可扩展的，组件是可拔插的”

请确认。

**Comment by rootsongjc** [comment]
@tangyong 请直接提交 PR 修复该问题。

**Comment by tangyong** [comment]
OK

**Comment by tangyong** [comment]
再次做了确认， @haiker2011 3.12日已经做了Review和提交， master是最新的，不用改了， 但是http://www.servicemesher.com/istio-handbook/concepts-and-principle/istio-architecture.html 还是错的，需要重新发布handbook @rootsongjc

**Comment by tangyong** [comment]
建议这个问题先不要关闭，等待handbook上与master同步后，再关闭， 另外， 建议http://www.servicemesher.com/istio-handbook 追加版本化， 与master/tags同步对应，这样读者不会感到困惑了，而且也会知道当前handbook处在最新还是上一个稳定版。

**Comment by rootsongjc** [comment]
本书已经重启了，该问题已过期。
