### ISSUE TITLE
多集群部署与管理: practice/multiple-cluster.md

### ISSUE THREAD

**Issue by 3ks** [servicemesher/istio-handbook#146]
This article is waiting to be claimed. [practice/multiple-cluster.md](https://github.com/servicemesher/istio-handbook/tree/master/practice/multiple-cluster.md)

**Comment by gorda** [comment]
Thank you @dwctua, this issue had been assigned to you.

**Comment by rootsongjc** [comment]
本文已发布，https://www.servicemesher.com/istio-handbook/practice/multiple-cluster.html
