### ISSUE TITLE
常见问题: practice/faq.md

### ISSUE THREAD

**Issue by gorda** [servicemesher/istio-handbook#148]
This article is waiting to be claimed. [practice/faq.md](https://github.com/servicemesher/istio-handbook/tree/master/practice/faq.md)

这一节内容先不用提交 PR，直接在该 issue 中回复讨论即可，最后快成书时，从这里选择合适的 FAQ 加入书中。对于复杂的问题也可以单独创建 Issue，然后使用 label `faq` 标记。

**Comment by zeusro** [comment]
Q: 为什么随着 `VirtualService` 的增多，感觉服务调用越来越慢？

A: `Isito` 以 `Sidecar Container` 注入的方式实现了流量的挟持，并由此拓展了 `Kubernetes` 提出的”服务“的概念。但无论  `Kubernetes service` 也好，`VirtualService` ，在很多旧版本都是以 `IPtables ` 规则形式存在。`IPtables` 本质上是一个串行执行的堆表，“表的数据”（路由规则)越多，执行效率越低。可参考：https://github.com/kubernetes/kubernetes/tree/master/pkg/proxy/ipvs
