### ISSUE TITLE
网格扩展和多集群配置的两个URL不正确

### ISSUE THREAD

**Issue by tangyong** [servicemesher/istio-handbook#15]
“服务网格的实现模式”章节中的子章节”多集群部署和扩展”中的
网格扩展和多集群配置的两个URL不正确：

1 https://preliminary.istio.io/zh/docs/setup/kubernetes/mesh-expansion/ 已经失效， 确认了一下应该为
https://preliminary.istio.io/zh/docs/setup/kubernetes/additional-setup/mesh-expansion/

2 https://preliminary.istio.io/zh/docs/setup/kubernetes/multicluster-install/ 已经失效，确认了一下未找到正确的中文地址。

以上请确认一下

**Comment by rootsongjc** [comment]
@tangyong 感谢你的反馈，请直接提交 PR 修复吧。

**Comment by tangyong** [comment]
@rootsongjc 多集群的安装这个URL， 除了英文的， 中文的现在都失效了， 是否写官方英文的？

**Comment by rootsongjc** [comment]
可以，直接换成英文的吧，最好用 https://isito.io 当前版本的，而不是预览版的链接，因为预览版链接还有调整的可能。

**Comment by tangyong** [comment]
OK
