### ISSUE TITLE
xDS: ecosystem/xds.md

### ISSUE THREAD

**Issue by 3ks** [servicemesher/istio-handbook#152]
This article is waiting to be claimed. [ecosystem/xds.md](https://github.com/servicemesher/istio-handbook/tree/master/ecosystem/xds.md)

**Comment by mlycore** [comment]
文章内容基本写好，需要完善 

/delay-reset

**Comment by rootsongjc** [comment]
已发布：https://www.servicemesher.com/istio-handbook/ecosystem/xds.html
