### ISSUE TITLE
流量控制: concepts/traffic-control.md

### ISSUE THREAD

**Issue by 3ks** [servicemesher/istio-handbook#162]
This article is waiting to be claimed. [concepts/traffic-control.md](https://github.com/servicemesher/istio-handbook/tree/master/concepts/traffic-control.md)

**Comment by tony-Ma-yami** [comment]
我公司项目最近升级,从阿里云迁移到aws云,  我同时实践了gloo, istio等, 同时在流量分发, 灰度发布这一块有大量的实践,并做了详细笔记, 自信在各种不同需求下的流量转发都有着最佳实践,  本着"学到的就要教给人"的宗旨, 所以想认领该issue, 希望社区考虑.

**Comment by ikingye** [comment]
> 我公司项目最近升级，从阿里云迁移到 aws 云，我同时实践了 gloo, istio 等，同时在流量分发，灰度发布这一块有大量的实践，并做了详细笔记，自信在各种不同需求下的流量转发都有着最佳实践，本着 "学到的就要教给人" 的宗旨，所以想认领该 issue, 希望社区考虑.

可以的，它现在是你的了。

**Comment by rootsongjc** [comment]
@tony-Ma-yami 请先阅读[参与流程](https://www.servicemesher.com/istio-handbook/wg/process.html)哈
