### ISSUE TITLE
关于图片格式、大小、命名规范

### ISSUE THREAD

**Issue by sunny0826** [servicemesher/istio-handbook#173]

**Comment by rootsongjc** [comment]
我建议图片的格式如下：
- 使用 PNG 或 JPG 格式
- Markdown 中必须指明图片的标题，即格式为 `![title](path)`
- 图片中的文字描述使用中文，专业名词可以使用英文（为了出版需要）
- 所有图片使用本地存储，放到 `images` 目录下
- 图片引用都使用相对路径
- 图片文件名全为小写，使用英文命名，单词间使用连字符连接
- 图片的分辨率不能太低，保证文字清晰，没有水印，没有与要表达的信息无关的内容，不如签名、链接
- 引用的图片请注明引用来源（附上 URL）
- 请勿使用人像照片
- 图片配色得体大方

我暂时想到这么多，大家再补充补充。

**Comment by sunny0826** [comment]
图片名称应该包括是属于哪篇文章的吧？比如：`{markdown-name}-{image-name}.png`

**Comment by rootsongjc** [comment]
@sunny0826 我觉得没有必要这样命名，因为章节还有文章本身的名字都可能会改动，而且一张图片可能会在不同的章节中重复出现，所以直接根据图片本身的主题命名即可。
