### ISSUE TITLE
Problem to see application in Jaeger with Istio demo profile

### ISSUE THREAD

**Issue by sudipju** [servicemesher/istio-handbook#255]
We have installed istio in demo mode in a GKE cluster..Then deployed springboot based java applications in the cluster, where istio 1.5.4 is enabled. But, we are not able to see them in Jaeger or Prometheus normally. Then, we compared what is there in book review sample application in istio and then found out they have virtual service and Gateway. When we added gateway and virtual service for our application then we see them coming in Jaeger.. Could you please help to understand the logic behind it? Is it mandatory to have virtual service and Gateway to have applications appeared in Jaeger?

Thanks in advance.

**Comment by rootsongjc** [comment]
@servicemesher/istio-handbook-maintainers He asked why must create VirtualService and Gateway to get the monitoring data in Jaeger.

**Comment by malphi** [comment]
The port 15032 is tracing user interface which is exposed by istio-ingressgateway.

**Comment by rootsongjc** [comment]
你好，为了便于 Istio 用户的交流，云原生社区创办了 [Istio SIG](https://github.com/cloudnativeto/sig-istio)，可以在那里交流和提问，此仓库已不再记录用户提问。
