### ISSUE TITLE
istio 流控规则下发配置生效问题

### ISSUE THREAD

**Issue by cuijiji** [servicemesher/istio-handbook#260]
再使用istio过程中 
1 我们增加新版本时  是增加dr 再增加vs  但是不清楚什么时候dr增加好了 可以增加vs
2 我们删除旧的版本 先删除vs  再删除dr 但是不清楚什么时候vs删除好了 可以删除dr
如何保障结果一致性
保障配置都在生效之后才开始下一步的操作

**Comment by malphi** [comment]
make before break 原则

**Comment by cuijiji** [comment]
> make before break 原则
> 使用 istioctl ps 查看配置的同步状态。即便是还没同步完成，你例举的问题也是可以自愈的。

多谢 我按照这个思路测试一下

**Comment by rootsongjc** [comment]
你好，为了便于 Istio 用户的交流，云原生社区创办了 [Istio SIG](https://github.com/cloudnativeto/sig-istio)，可以在那里交流和提问，此仓库已不再记录用户提问。
