### ISSUE TITLE
对等认证: practice/peer-authentication.md

### ISSUE THREAD

**Issue by sunny0826** [servicemesher/istio-handbook#268]
This article is waiting to be claimed. [practice/peer-authentication.md](practice/peer-authentication.md)

**Comment by mcsos** [comment]
这一节的内容好像被写到了"请求认证"一节中，https://www.servicemesher.com/istio-handbook/practice/request-authentication.html。

**Comment by rootsongjc** [comment]
「请求认证」一节中有写吗？没在里面找到啊

**Comment by mcsos** [comment]
"对等认证"一节目前的内容是空的，实际上本来应该是"对等认证"的内容被写到了"请求认证"一节中，我提交了一个pr把这些内容移过来。
