### ISSUE TITLE
请教关于Istio南北向网关实现？

### ISSUE THREAD

**Issue by cnicy** [servicemesher/istio-handbook#280]
社区大佬们，请教一个问题，Istio南北流量安全策略一般是怎么做的呢？现在做法是放在业务系统网关一般包含几个功能：SSL终结、JWT鉴权、服务访问鉴权、流量治理（限流、熔断、灰度等）等，如果采用Istio之后IstioGateway网关是不是能去哪不hold住业务系统的网关功能，是不是就不需要业务系统的网关了？
现有业务系统网关示意图：
![image](https://user-images.githubusercontent.com/3939815/85943712-66c0c900-b964-11ea-9f31-b45ef097110d.png)

**Comment by hb-chen** [comment]
SSL终结可以，有关JWT认证、鉴权可以看下这个[JWT 授权](https://www.servicemesher.com/istio-handbook/practice/jwt-authorization.html#ingress-jwt-%E8%AE%A4%E8%AF%81)，流量治理相关的也有[流量控制](https://www.servicemesher.com/istio-handbook/practice/traffic-control.html)

**Comment by rootsongjc** [comment]
你好，为了便于 Istio 用户的交流，云原生社区创办了 [Istio SIG](https://github.com/cloudnativeto/sig-istio)，可以在那里交流和提问，此仓库已不再记录用户提问。
