### ISSUE TITLE
请教一个问题，istio 偶尔会报这个错误 upstream connect error or disconnect/reset before headers

### ISSUE THREAD

**Issue by WudyH** [servicemesher/istio-handbook#288]
istio 偶尔会报这个错误
upstream connect error or disconnect/reset before headers. reset reason: overflow.
请问要找出问题并解决。

谢谢！

**Comment by malphi** [comment]
overflow: 熔断了

**Comment by WudyH** [comment]
请问是哪里配置有问题？要怎样修改。

感谢！

**Comment by malphi** [comment]
你看一下destinationrule里面的trafficpolicy那块是怎么配置的，outlierDetection负责熔断

**Comment by WudyH** [comment]
@malphi 现在没有配置destinationrule，destinationrule要怎样配置？

谢谢！

**Comment by wbpcode** [comment]
@WudyH  看一下这个 https://istio.io/latest/docs/reference/config/networking/destination-rule/

**Comment by wbpcode** [comment]
overflow 应该是溢出了，超出了最大的可 pending 请求数，一般是网络抖动或者后端服务太慢导致请求在sidecar中淤塞引起的。

**Comment by WudyH** [comment]
> overflow 应该是溢出了，超出了最大的可 pending 请求数，一般是网络抖动或者后端服务太慢导致请求在sidecar中淤塞引起的。istio 社区从 1.4 之后，修改了熔断相关的配置的默认值，几乎都改成了默认不做任何限制。

现在是这样配置的：

kind: DestinationRule
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: xserver2-destinationrule-asxxxxxx
  namespace: xserver2
spec:
  host: asxxxxx
  trafficPolicy:
    connectionPool:
      tcp:
        connectionTimeout: 30ms
        maxConnections: 10000
        tcpKeepalive:
          interval: 75s
          time: 7200s

**Comment by wbpcode** [comment]
@WudyH 当前的 dr 配置解决了溢出的问题嘛？一般来说，需要配置 http 中的 http1MaxPendingRequests 字段。最简单的是直接把 istio 升级到 1.4 以上，回避这个问题。

**Comment by WudyH** [comment]
@wbpcode 
现在还会报这个错误：
upstream connect error or disconnect/reset before headers. reset reason: connection termination.

这个也是溢出引起的问题吗？

**Comment by wbpcode** [comment]
> @wbpcode
> 现在还会报这个错误：
> upstream connect error or disconnect/reset before headers. reset reason: connection termination.
> 
> 这个也是溢出引起的问题吗？

这个原因有多种，如果上游服务没有发生 crash 或者意外重启的话，一般是另一个问题引起的，上游服务一般都会有一个空闲连接保持时间，如果到期就会断开，但是 envoy 默认是不会断开连接的。在上游断开之后，enovy 收到 FIN 包之前的这么一小段时间，如果 envoy 继续通过这个连接发送请求，就会触发这个错误。你可以搜索一下 envoy upstream idleTimeout 这么个东西，应该就可以找到解决方案。

**Comment by rootsongjc** [comment]
你好，为了便于 Istio 用户的交流，云原生社区创办了 [Istio SIG](https://github.com/cloudnativeto/sig-istio)，可以在那里交流和提问，此仓库已不再记录用户提问。
