### ISSUE TITLE
istioctl中发现hub的一些默认的仓库地址， 是否因为这个，导致修改default.yaml中的仓库地址不生效

### ISSUE THREAD

**Issue by graysonfan** [servicemesher/istio-handbook#299]

**Comment by rootsongjc** [comment]
你可以在 issue 里详细描述下过程还有现象吗？

**Comment by graysonfan** [comment]
![微信截图_20200720144946](https://user-images.githubusercontent.com/9099026/87908119-7e3d2e80-ca98-11ea-9f1d-ea038d233fbe.png)

**Comment by graysonfan** [comment]
istioctl中有镜像的地址， 我们的部署环境是内网环境，无法修改使用内网的harbor仓库地址

**Comment by graysonfan** [comment]
我尝试修改了
![image](https://user-images.githubusercontent.com/9099026/87908275-b2185400-ca98-11ea-933e-a3ebab063f3c.png)

**Comment by graysonfan** [comment]
![image](https://user-images.githubusercontent.com/9099026/87908377-da07b780-ca98-11ea-93f3-209f5560968e.png)
![image](https://user-images.githubusercontent.com/9099026/87908430-f1df3b80-ca98-11ea-8dea-60767ce6a377.png)

 我尝试修改，但是doubuqizu都不起作用，仍然还是docker.io/xx.xx

**Comment by rootsongjc** [comment]
你好，为了便于 Istio 用户的交流，云原生社区创办了 [Istio SIG](https://github.com/cloudnativeto/sig-istio)，可以在那里交流和提问，此仓库已不再记录用户提问。
