### ISSUE TITLE
点击 istio-handbook 左边侧栏切换页面响应耗时长

### ISSUE THREAD

**Issue by Miss-you** [servicemesher/istio-handbook#332]
![image](https://user-images.githubusercontent.com/3816205/93435466-15d5c680-f8fc-11ea-9202-48a306682711.png)

点击 istio-handbook 左边侧栏切换页面响应耗时长，经常点击一下都没反应，要点击好几次。

**Comment by rootsongjc** [comment]
这种情况可能是因为你访问的时候带宽被打满了，我现在访问没有遇到卡顿的情况。

**Comment by rootsongjc** [comment]
因为无法付现，关闭该 issue。
