### ISSUE TITLE
Istio Handbook 开源电子书重启

### ISSUE THREAD

**Issue by rootsongjc** [servicemesher/istio-handbook#42]
最近 ServiceMesher 社区做了一次 [Service Mesh 终端用户问卷调查](https://www.servicemesher.com/blog/service-mesh-end-user-survey-report/)，结果是有点出乎我的意料的，4000 多人的社区，只有 500 多人填写了问卷，回收率只有 12%左右。问卷填写者 94.2% 来自 ServiceMesher 社区，21.7% 的人参与过社区线上活动，27.5% 的人参与过社区 meetup，86.6% 看好 Service Mesh 的未来发展前景。可以说这些人是 Service Mesh 的铁粉了。

但是从问卷收集上来的 100 多份的建议来看，大部分人还是希望社区能够多一些入门指导、实践指南和落地案例等，所以我想是时候重启本书了。**请愿意共同参与本书开源写作的同学，在本 issue 中回复 +1，当达到一定人数后，我们将开始正式重启本书。**

我们应该将 Service Mesh 的思想沉淀出来，我们提倡知行合一，鼓舞更多的人参与进来，将自己学习和实践整理出来，不当神手党，在获取的同时能够给予，赠人玫瑰手有余香，只有你能用通俗的话语让别人明白，那才是真正掌握了知识，如果能在知识的基础上变得更加透彻了悟，那就是智慧了。

## 如何参与

请各位参与者[在此登记](https://docs.google.com/spreadsheets/d/1uCv1zrf8v11woqEYilDR3GkRgznaLtlkbJyKlyNiMHg/edit?usp=sharing)，然后扫描下面的二维码加入协作钉钉群（请备注在表格中登记的 GitHub ID）。

![image](https://user-images.githubusercontent.com/3328185/76673185-9dedb300-65dd-11ea-877c-81d48bb7749d.png)

**Comment by justmine66** [comment]
1

**Comment by adlerliu** [comment]
1

**Comment by LamboChen** [comment]
1

**Comment by LamboChen** [comment]
1

**Comment by LamboChen** [comment]
1

**Comment by GuangmingLuo** [comment]
+1

**Comment by wxing2008666** [comment]
+1

**Comment by NIUYULEE** [comment]
+1

**Comment by Morgan-1** [comment]
+1

**Comment by yuxiaoba** [comment]
+1

**Comment by halfsre** [comment]
+1

**Comment by axot** [comment]
nice +1

**Comment by noahbentusi** [comment]
支持  +1

**Comment by aixiaoxiang** [comment]
+1

**Comment by rhuanhuan** [comment]
+1

**Comment by shellgithub** [comment]
+1

**Comment by csdnshyang** [comment]
+1

**Comment by it2911** [comment]
+1

**Comment by qunqiang** [comment]
1

**Comment by baikai** [comment]
+1

**Comment by Gamehu** [comment]
+1

**Comment by leozhang0227** [comment]
+1

**Comment by scwang18** [comment]
+1

**Comment by xue8** [comment]
+1

**Comment by yatwql** [comment]
+1

**Comment by kevinsingapore** [comment]
+1

**Comment by rainment** [comment]
+1

**Comment by dangpf** [comment]
+1

**Comment by adairliulei** [comment]
+1

**Comment by flipped0908** [comment]
+1

**Comment by flipped0908** [comment]
#

**Comment by bigdimple** [comment]
+1

**Comment by Aisuko** [comment]
+1

**Comment by lluxury** [comment]
+1

**Comment by hmwenchen** [comment]
+1

**Comment by lengrongfu** [comment]
1

**Comment by lengrongfu** [comment]
+1

**Comment by ikingye** [comment]
+1

**Comment by rootsongjc** [comment]
既然大家的热情这么高，那我们明天就要准备开始了，请各位参与者[在此登记](https://docs.google.com/spreadsheets/d/1uCv1zrf8v11woqEYilDR3GkRgznaLtlkbJyKlyNiMHg/edit?usp=sharing)，我们后续将创建单独的钉钉群，用来作为参加者沟通交流。

**Comment by TomMorant** [comment]
+1

**Comment by markwu100** [comment]
+1

**Comment by markwu100** [comment]
+1

**Comment by dwctua** [comment]
+1

**Comment by wangzewang** [comment]
+1

**Comment by chding99** [comment]
+1

**Comment by ldaysjun** [comment]
+1

**Comment by FengyunPan2** [comment]
+1

**Comment by fly88oj** [comment]
+1

**Comment by sifksky** [comment]
+1

**Comment by gorda** [comment]
+1

**Comment by meua** [comment]
+1

**Comment by noshenxian** [comment]
+1

**Comment by yhyddr** [comment]
看好中国社区的发展,+1

**Comment by wangqiongkaka** [comment]
+1

**Comment by xianyuLuo** [comment]
+1

**Comment by russellgao** [comment]
+1

**Comment by zeroingsu** [comment]
+1

**Comment by owen-sun** [comment]
+1

**Comment by owen-sun** [comment]
+1

**Comment by edenzhong7** [comment]
+1

**Comment by superzhengzhe** [comment]
+1

**Comment by MrCocoaCat** [comment]
+1

**Comment by Yngda** [comment]
> 最近 ServiceMesher 社区做了一次 [Service Mesh 终端用户问卷调查](https://www.servicemesher.com/blog/service-mesh-end-user-survey-report/)，结果是有点出乎我的意料的，4000 多人的社区，只有 500 多人填写了问卷，回收率只有 12%左右。问卷填写者 94.2% 来自 ServiceMesher 社区，21.7% 的人参与过社区线上活动，27.5% 的人参与过社区 meetup，86.6% 看好 Service Mesh 的未来发展前景。可以说这些人是 Service Mesh 的铁粉了。
> 
> 但是从问卷收集上来的 100 多份的建议来看，大部分人还是希望社区能够多一些入门指导、实践指南和落地案例等，所以我想是时候重启本书了。**请愿意共同参与本书开源写作的同学，在本 issue 中回复 +1，当达到一定人数后，我们将开始正式重启本书。**
> 
> 我们应该将 Service Mesh 的思想沉淀出来，我们提倡知行合一，鼓舞更多的人参与进来，将自己学习和实践整理出来，不当神手党，在获取的同时能够给予，赠人玫瑰手有余香，只有你能用通俗的话语让别人明白，那才是真正掌握了知识，如果能在知识的基础上变得更加透彻了悟，那就是智慧了。
> 
> ## 如何参与
> 请各位参与者[在此登记](https://docs.google.com/spreadsheets/d/1uCv1zrf8v11woqEYilDR3GkRgznaLtlkbJyKlyNiMHg/edit?usp=sharing)，然后扫描下面的二维码加入协作钉钉群（请备注在表格中登记的 GitHub ID）。
> 
> ![image](https://user-images.githubusercontent.com/3328185/74722551-162db680-5274-11ea-9b1e-899061adfef5.png)

+1

**Comment by Yngda** [comment]
+1

**Comment by Lovnx** [comment]
+1x

**Comment by SmileSees** [comment]
+1

**Comment by jiangydev** [comment]
+1

**Comment by Dereking** [comment]
+1

**Comment by koonchen** [comment]
+1

**Comment by sunney2010** [comment]
+1

**Comment by tscswcn** [comment]
+1

**Comment by wenhuwang** [comment]
+1

**Comment by ZhangBohan1987** [comment]
+1

**Comment by scwang18** [comment]
+1

**Comment by idefav** [comment]
+1

**Comment by f2h2h1** [comment]
+1

**Comment by exuan** [comment]
+1

**Comment by zjjay** [comment]
+1

**Comment by lilinji** [comment]
+1

**Comment by yuxiaobo96** [comment]
+1

**Comment by JaredTan95** [comment]
+1

**Comment by wuti1609** [comment]
+1

**Comment by zhikun0704** [comment]
+1

**Comment by token01** [comment]
+1

**Comment by ljavargo** [comment]
+1

**Comment by hb-chen** [comment]
+1

**Comment by rootsongjc** [comment]
最新进展同步：今晚（2 月 28 日）本书编委会将进行 kickoff。

**Comment by rootsongjc** [comment]
## Istio Handbook Kickoff

Istio Handbook 编委会 2 月 28 日晚进行了本书的 kickoff，以下是会议结论同步给大家。

### 本书定位、愿景

以开源社区的方式，通过开源协作来共同编写一本简洁概要、高度概括、**通俗易懂**、包含示例的纯干货电子书。

### 内容提要

本书内容包括以下章节。

#### 概念（P0）

通俗易懂的概念讲解。

#### 原理（P1）

可以根据已有精华博客收录，通过摘抄或引用（注明来源），分类到不同的原理说明中，如流量控制、可观察性、安全。

#### 实践（P2）：核心部分

- Task：与环境解耦，每个 task 可以独立实现；
- Best practice：针对于每个场景的一种解决方案；
- 整合：整合其他系统（比如 Prometheus、Skywalking、配置中心）、Dubbo、SpringCloud

#### 源码（P3）

根据实践来确定需要哪些源码分析。

---

本书的筹备工作仍在进行中，如有问题请在本 issue 或协作钉钉群中反馈。谢谢。

**Comment by rootsongjc** [comment]
## 最新进展通告

2020年03月13日晚经过本书[编委会](https://www.servicemesher.com/istio-handbook/wg/editorial-board.html)讨论，通过了 [Istio Handbook 目录 v0.2](https://github.com/servicemesher/istio-handbook/blob/master/wg/toc.md) 草案，请大家查阅，有任何问题可以在当前 issue 中回复。

下一步编委会将开始着手本书的编写，也希望大家多提意见和参与到本书中来。

**Comment by dwctua** [comment]
hybrid cloud/multi-cluster config 是哪一章？

**Comment by rootsongjc** [comment]
@dwctua 你说的这个应该是在安装与部署中，在讨论本书目录的时候编委会也考虑到了这个需求，但是觉得这部分内容可能与厂商关系比较紧密及 Istio 官网本身已有详细说明，暂时没有列在里面。如果读者需求强烈，或者有人愿意贡献或者 lead 这部分内容可以与我们编委会联系。

**Comment by rootsongjc** [comment]
@dwctua  你说的这个应该是在安装与部署中，在讨论本书目录的时候编委会也考虑到了这个需求，但是觉得这部分内容可能与厂商关系比较紧密及 Istio 官网本身已有详细说明，暂时没有列在里面。如果读者需求强烈，或者有人愿意贡献或者 lead 这部分内容可以与编委会联系。

**Comment by dwctua** [comment]
我个人对这块比较感兴趣，但不知道群里感兴趣的多不多。有机会我可以写几篇，抛砖引玉吧。

**Comment by dwctua** [comment]
我还建议加入有关microsoft OAM 的章节， 我也特别想看看大家是如和考虑与Istio的集成方案

**Comment by rootsongjc** [comment]
@dunjut 可以直接提交issue，让编委会和读者来评估吧。

**Comment by rootsongjc** [comment]
本书的编写中断了有几个月时间，现在又要重启了，我们组成了新的编写小组，为了配合出版需要，剩余内容将在新的私有仓库中编写，感谢大家的关注！

**Comment by zyjiang-storehub** [comment]
+1

**Comment by StruggleYang** [comment]
> 本书的编写中断了有几个月时间，现在又要重启了，我们组成了新的编写小组，为了配合出版需要，剩余内容将在新的私有仓库中编写，感谢大家的关注！

现在还能参与编写吗？

**Comment by rootsongjc** [comment]
@StruggleYang 直接与我联系吧。

**Comment by zhi-gang-sun** [comment]
> 本书的编写中断了有几个月时间，现在又要重启了，我们组成了新的编写小组，为了配合出版需要，剩余内容将在新的私有仓库中编写，感谢大家的关注！

求参与 @rootsongjc

**Comment by lilinji** [comment]
+1

**Comment by xcbeyond** [comment]
+1

**Comment by rootsongjc** [comment]
感谢大家的支持。本书已临近出版，且该仓库已不再维护，不再接受新的作者。
