### ISSUE TITLE
建议增加有关istio在hybrid cloud 和multi-cluster 应用的相关内容

### ISSUE THREAD

**Issue by dwctua** [servicemesher/istio-handbook#50]
现在大部分Enterprisie应用都是在hybrid cloud的环境下运行， istio对multi-cluster的应用管理提供了一个新的模式。有关于这方面的讨论应该是很有帮助的。

**Comment by rootsongjc** [comment]
@servicemesher/istio-doc-wg 大家怎么看？放在哪个章节合适？

**Comment by GuangmingLuo** [comment]
可以放在进阶实践下，创建一个子目录：多集群部署与管理

**Comment by rootsongjc** [comment]
@GuangmingLuo 这个就是在“部署模型”中加入一个分支即可吧。

**Comment by sunny0826** [comment]
这个应该算是部署模型的一部分吧？
