### ISSUE TITLE
Istio 功能介绍: concepts/features.md

### ISSUE THREAD

**Issue by 3ks** [servicemesher/istio-handbook#59]
This article is waiting to be claimed. [concepts/features.md](https://github.com/servicemesher/istio-handbook/tree/master/concepts/features.md)

**Comment by linda01232003** [comment]
/pushed
https://github.com/servicemesher/istio-handbook/pull/185

**Comment by rootsongjc** [comment]
现在已经没有 `concepts/features` 目录了，改成了 `concepts/core-features` 了，”路由“一节改成了”流量控制“，现已完成。关闭此 issue。
