### ISSUE TITLE
VirtualService: concepts/virtualservice.md

### ISSUE THREAD

**Issue by gorda** [servicemesher/istio-handbook#70]
This article is waiting to be claimed. [concepts/virtualservice.md](https://github.com/servicemesher/istio-handbook/tree/master/concepts/virtualservice.md)

**Comment by ycliu912** [comment]
[#70](https://github.com/servicemesher/istio-handbook/issues/70)

**Comment by sunny0826** [comment]
目录调整，该章节合并，详情见 #251
