### ISSUE TITLE
熔断: concepts/circuit-breaking.md

### ISSUE THREAD

**Issue by gorda** [servicemesher/istio-handbook#77]
This article is waiting to be claimed. [concepts/circuit-breaking.md](https://github.com/servicemesher/istio-handbook/tree/master/concepts/circuit-breaking.md)

**Comment by tony-Ma-yami** [comment]
Hi， 之前不知道每个目录下的子目录都是作为一个子Issue分开的，所以就把父目录下所有东西都写了。 与您这些的有点重复了。 感觉扔掉可惜。 回头您看有需要的话我们merge下。

**Comment by sunny0826** [comment]
目录调整，该章节合并，详情见 #251
