### ISSUE TITLE
分布式追踪: concepts/distributed-tracing.md

### ISSUE THREAD

**Issue by gorda** [servicemesher/istio-handbook#90]
This article is waiting to be claimed. [concepts/distributed-tracing.md](https://github.com/servicemesher/istio-handbook/tree/master/concepts/distributed-tracing.md)

**Comment by gorda** [comment]
Thank you @vsover, this issue had been assigned to you.

**Comment by sunny0826** [comment]
目录调整，该章节合并，详情见 #251
