### ISSUE TITLE
Kubernetes: practice/setup-in-kubernetes.md

### ISSUE THREAD

**Issue by gorda** [servicemesher/istio-handbook#95]
This article is waiting to be claimed. [practice/setup-in-kubernetes.md](https://github.com/servicemesher/istio-handbook/tree/master/practice/setup-in-kubernetes.md)

**Comment by rootsongjc** [comment]
这篇文章取消，将与 https://www.servicemesher.com/istio-handbook/practice/setup-istio.html 合并。
