### ISSUE TITLE
虚拟机: practice/setup-in-vm.md

### ISSUE THREAD

**Issue by gorda** [servicemesher/istio-handbook#96]
This article is waiting to be claimed. [practice/setup-in-vm.md](https://github.com/servicemesher/istio-handbook/tree/master/practice/setup-in-vm.md)

**Comment by sunny0826** [comment]
本节取消，我们仅支持最流行的基于 Kubernetes 的部署，其他部署方式如果有需求可以再提交 PR 补充。详见：https://github.com/servicemesher/istio-handbook/pull/198
